# Generated by Django 3.2.16 on 2023-03-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='primary_delivery_location',
            field=models.CharField(default='kingston', max_length=150),
        ),
        migrations.AddField(
            model_name='partner',
            name='secondary_delivery_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
