# Generated by Django 3.2.16 on 2023-03-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20230306_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='slug',
            field=models.SlugField(default='partner', max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
