# Generated by Django 3.2.16 on 2023-03-09 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partner_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='slug',
        ),
    ]
