# Generated by Django 3.2.16 on 2023-02-15 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stalls', '0024_auto_20230215_1038'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stall',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stall_owned', to='Stalls.stall', verbose_name='Stall'),
        ),
    ]
