# Generated by Django 3.2.16 on 2022-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_delivery_location', models.CharField(blank=True, max_length=150, null=True)),
                ('secondary_delivery_location', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
