# Generated by Django 3.2.16 on 2022-11-27 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='owner',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customeuser', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
    ]
