# Generated by Django 3.2.16 on 2022-12-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stalls', '0002_stall_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='image',
            field=models.ImageField(default='none', max_length=200, null=True, upload_to='stall_img'),
        ),
    ]
