# Generated by Django 3.2.16 on 2022-12-05 20:32

from django.db import migrations, models
import django.db.models.deletion
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('Stalls', '0003_stall_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stall',
            name='image',
            field=models.ImageField(default='download.png', max_length=200, null=True, upload_to='images/stall_img'),
        ),
        migrations.CreateModel(
            name='StallStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_currency', models.CharField(default=oscar.core.utils.get_default_currency, max_length=12, verbose_name='Currency')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price')),
                ('num_in_stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number in stock')),
                ('num_allocated', models.IntegerField(blank=True, null=True, verbose_name='Number allocated')),
                ('low_stock_threshold', models.PositiveIntegerField(blank=True, null=True, verbose_name='Low Stock Threshold')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to='Stalls.stall', verbose_name='owner')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stallstockrecords', to='catalogue.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stall Stock',
                'verbose_name_plural': 'Stall Stocks',
            },
        ),
    ]
