# Generated by Django 3.2.16 on 2022-12-09 18:50

from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('Stalls', '0004_auto_20221205_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalogue.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='stall',
            name='slug',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='stallstock',
            name='price_currency',
            field=models.CharField(default='JMD', max_length=12, verbose_name='Currency'),
        ),
    ]
