# Generated by Django 3.2.16 on 2022-12-09 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('Stalls', '0005_auto_20221209_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='category',
            field=models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, to='catalogue.category', verbose_name='Category'),
        ),
    ]
