# Generated by Django 3.2.16 on 2022-12-10 17:41

from django.db import migrations
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ('Stalls', '0005_auto_20221210_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='code',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, default='name', editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Code'),
        ),
    ]
