# Generated by Django 3.2.16 on 2022-12-10 17:46

from django.db import migrations, models
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ('Stalls', '0006_alter_stall_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='code',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, default=models.CharField(blank=True, max_length=255, null=True), editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Code'),
        ),
    ]
