# Generated by Django 3.2.16 on 2022-12-09 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stalls', '0007_auto_20221209_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stallstock',
            name='price_currency',
            field=models.CharField(default='JMD', max_length=12, verbose_name='Currency'),
        ),
    ]
