# Generated by Django 3.2.16 on 2022-12-09 23:15

from django.db import migrations, models
import oscar.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('Stalls', '0008_alter_stallstock_price_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='slug',
        ),
        migrations.AlterField(
            model_name='stallstock',
            name='price_currency',
            field=models.CharField(default=oscar.core.utils.get_default_currency, max_length=12, verbose_name='Currency'),
        ),
    ]
