# Generated by Django 3.2.16 on 2022-12-10 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stalls', '0009_auto_20221209_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='code',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stall',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customeuser', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='stallstock',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
