# Generated by Django 3.2.16 on 2022-12-10 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stalls', '0010_auto_20221210_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stallstock',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='stallstock',
            name='price_currency',
            field=models.CharField(default='JMD', max_length=12, verbose_name='Currency'),
        ),
    ]
