# Generated by Django 3.2.16 on 2022-12-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stalls', '0005_auto_20221210_0944'),
        ('Stalls', '0005_auto_20221210_0946'),
        ('Stalls', '0007_alter_stall_code'),
        ('Stalls', '0012_alter_stall_owner'),
    ]

    operations = [
    ]
