# Generated by Django 3.2.16 on 2022-12-10 20:04

from django.db import migrations, models
import django.db.models.deletion
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('Stalls', '0013_merge_20221210_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalogue.category', verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stall',
            name='code',
            field=oscar.models.fields.autoslugfield.AutoSlugField(blank=True, editable=False, max_length=128, populate_from='name', unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='stallstock',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customuser', to='Stalls.stall', verbose_name='owner'),
        ),
    ]
