# Generated by Django 3.2.16 on 2022-12-13 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stalls', '0015_alter_stall_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stall',
            old_name='phone',
            new_name='contact_number',
        ),
        migrations.AddField(
            model_name='stall',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stallstockrecords', to='Stalls.stallstock', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='stallstock',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stall',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='customeuser', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
    ]
