# Generated by Django 3.2.16 on 2022-12-13 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stalls', '0017_remove_stall_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='owner',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='customeuser', to='customer.customuser', verbose_name='Manager'),
            preserve_default=False,
        ),
    ]
