# Generated by Django 3.2.16 on 2022-12-13 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stalls', '0018_stall_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='owner',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, related_name='customeuser', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
    ]
