# Generated by Django 3.2.16 on 2022-12-13 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stalls', '0020_alter_stall_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='image',
            field=models.ImageField(default='download.png', max_length=200, null=True, upload_to=''),
        ),
    ]
