# Generated by Django 3.2.16 on 2023-02-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
        ('Stalls', '0024_auto_20230215_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='catalogue.category', verbose_name='Category'),
        ),
    ]
